<?php

/**
 * @file
 * Contains seeds_development.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function seeds_development_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
  // Main module help for the seeds_development module.
  case 'help.page.seeds_development':
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provides helpful functionalities for developers') . '</p>';
    return $output;

  default:
  }
}

function create_inspect_operation($route_name, $params = []) {
  return [
    'title' => t('Inspect'),
    'url' => Url::fromRoute($route_name, $params),
    'weight' => 99,
  ];
}

/**
 * Implements hook_entity_operation_alter().
 */

function seeds_development_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == "image_style") {
    /** @var \Drupal\image\Entity\ImageStyle $entity */
    $operations['inspect'] = create_inspect_operation('seeds_development.image_style', ['image_style' => $entity->id()]);
  }
}