<?php

/**
 * Implements hook_panels_layouts().
 */
// Plugin definition
$plugin = array(
  'title' => t('Seeds Right'),
  'category' => t('Seeds'),
  'icon' => 'seeds_right.png',
  'theme' => 'seeds-right',
  'regions' => array(
    'separator' => t('Separator'),
    'separator1' => t('Separator'),
    'separator2' => t('Separator'),
  	'separator3' => t('Separator'),
  	'separator4' => t('Separator'),
  	'separator5' => t('Separator'),
  	'separator6' => t('Separator'),
    'left' => t('Left side'),
    'middle' => t('Middle column'),
    'right' => t('Right side'),
    'left1' => t('Left side'),
    'right1' => t('Right side'),
    'left2' => t('Left side'),
    'right2' => t('Right side'),
    'left3' => t('Left side'),
    'right3' => t('Right side'),
    'left4' => t('Left side'),
    'right4' => t('Right side'),
    'left5' => t('Left side'),
    'right5' => t('Right side'),
    'left6' => t('Left side'),
    'right6' => t('Right side'),
  ),
);
