<?php

/**
 * Implements hook_panels_layouts().
 */
// Plugin definition
$plugin = array(
  'title' => t('Seeds Basic'),
  'category' => t('Seeds'),
  'icon' => 'seeds_basic.png',
  'theme' => 'seeds-basic',
  'regions' => array(
    'separator' => t('Separator'),
    'separator1' => t('Separator'),
    'separator2' => t('Separator'),
    'left' => t('Left side'),
    'middle' => t('Middle column'),
    'right' => t('Right side'),
    'separator3' => t('Separator'),
    'separator4' => t('Separator'),
    'separator5' => t('Separator'),
    'separator6' => t('Separator'),
    'left1' => t('Left side'),
    'right1' => t('Right side'),
    'left2' => t('Left side'),
    'right2' => t('Right side'),
    'separator7' => t('Separator'),
    'separator8' => t('Separator'),
    'left3' => t('Left side'),
    'right3' => t('Right side'),
    'left4' => t('Left side'),
    'right4' => t('Right side'),
    'separator9' => t('Separator'),
    'separator10' => t('Separator'),
    'separator11' => t('Separator'),
  ),
);
