<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Functions to support adminimal admin toolbar.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function seeds_pollination_preprocess_html(&$variables) {
  // Add seeds-toolbar class to the body.
  if (_adminimal_admin_toolbar_is_access()) {
    $variables['attributes']['class'][] = 'seeds-toolbar';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function seeds_pollination_page_attachments_alter(array &$page) {
  // Attaches css assets globally.
  if (_adminimal_admin_toolbar_is_access()) {
    $page['#attached']['library'][] = 'seeds_pollination/seeds-toolbar';
  }
}

/**
 * Implements hook_form_alter().
 */
function seeds_pollination_form_node_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $title = $form['title']['widget'][0]['value']['#title'];
  $form['title']['widget'][0]['value']['#title_display'] = 'hidden';
  $form['title']['widget'][0]['value']['#placeholder'] = $title;
}
