<?php

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_ckeditor_css_alter().
 *
 * Load frontend theme stylesheet into ckeditor.
 */
function seeds_editor_ckeditor_css_alter(array &$css, Editor $editor) {
  if (!$editor->hasAssociatedFilterFormat()) {
    return;
  }
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  // Uncomment this line and replace THEMENAME with your frontend theme name.
  // $css[] = drupal_get_path('theme', 'THEMENAME') . '/css/style.css';
  switch ($language) {
    case 'ar':
      // Uncomment this line and replace THEMENAME with your frontend theme name.
      // $css[] = drupal_get_path('theme', 'THEMENAME') . '/css/style-rtl.css';
      break;

    default:
      break;
  }
}
